print(10>7)
print(59>67)
print(67==34)
print(45<=47)
print(24!=45)
print(12>=67)
print("--------------------")
print(True and True)
print(True and False)
print(False and True )
print(False and False)
print("------------")
print(True or True)
print(True or False)
print(False or False)
print(False or True)